# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - release

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Validation
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Validation
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: "Subscription"
              azureResourceManagerConnection: "sasatake-azure-service-connection"
              subscriptionId: $(subscriptionId)
              location: "Japan East"
              templateLocation: "Linked artifact"
              csmFile: "azuredeploy.json"
              csmParametersFile: "azuredeploy.parameters.json"
              deploymentMode: "Validation"

  - stage: Release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    jobs:
      - job: Release
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: "Subscription"
              azureResourceManagerConnection: "sasatake-azure-service-connection"
              subscriptionId: $(subscriptionId)
              location: "Japan East"
              templateLocation: "Linked artifact"
              csmFile: "azuredeploy.json"
              csmParametersFile: "azuredeploy.parameters.json"
              deploymentMode: "Incremental"
