# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

variables:
  prefix: "$(Build.SourceBranchName)"
  resourceGroupName: "$(prefix)-rg"
  location: "japaneast"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Preparation
    jobs:
    - job: CreateResourceGroup
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'sasatake-azure-service-connection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              isExisted=$(az group exists -g ${1})
              if [ ${isExisted} == 'false' ];then
                az group create -g ${1} -l ${2};
              fi
            arguments: "$(resourceGroupName) $(location)"

  - stage: Validation
    dependsOn:
      - Preparation
    jobs:
      - job: ValidateTemplate
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: "sasatake-azure-service-connection"
              subscriptionId: $(subscriptionId)
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              templateLocation: "Linked artifact"
              csmFile: "azuredeploy.json"
              csmParametersFile: "azuredeploy.parameters.json"
              overrideParameters: "-prefix $(prefix)"
              deploymentMode: "Validation"

  - stage: Release
    dependsOn:
      - Validation
    jobs:
      - job: ProvisionResources
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: "sasatake-azure-service-connection"
              subscriptionId: $(subscriptionId)
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              templateLocation: "Linked artifact"
              csmFile: "azuredeploy.json"
              csmParametersFile: "azuredeploy.parameters.json"
              overrideParameters: "-prefix $(prefix)"
              deploymentMode: "Incremental"
